### PR TITLE
v252 batch

### PR DESCRIPTION
**Pull request by bluca**

### CODE REVIEW

**Comment by bluca** [comment]
@mrc0mmand @yuwata any idea about this? I don't see any network changes in this PR

```
21:26:37 ======================================================================
21:26:37 FAIL: test_qdisc_htb_fifo (__main__.NetworkdTCTests)
21:26:37 ----------------------------------------------------------------------
21:26:37 Traceback (most recent call last):
21:26:37   File "./test/test-network/systemd-networkd-tests.py", line 3555, in test_qdisc_htb_fifo
21:26:37     self.assertRegex(output, 'class htb 2:37 root leaf 37:')
21:26:37 AssertionError: Regex didn't match: 'class htb 2:37 root leaf 37:' not found in 'class htb 2:3b root leaf 3bprio 1 quantum 6250 rate 1Mbit ceil 500Kbit linklayer ethernet burst 1600b/1mpu 0b cburst 1600b/1mpu 0b level 0 \nclass htb 2:3a root leaf 3aprio 1 quantum 6250 rate 1Mbit ceil 500Kbit linklayer ethernet burst 1600b/1mpu 0b cburst 1600b/1mpu 0b level 0 \nclass htb 2:37 root leaf 37prio 1 quantum 4000 rate 1Mbit overhead 100 ceil 500Kbit linklayer ethernet burst 123456b/1mpu 0b cburst 123457b/1mpu 0b level 0 \nclass htb 2:3c root leaf 3cprio 1 quantum 6250 rate 1Mbit ceil 500Kbit linklayer ethernet burst 1600b/1mpu 0b cburst 1600b/1mpu 0b level 0'
```

**Comment by bluca** [comment]
never mind, happens in main too

**Comment by yuwata** [comment]
@bluca 
> never mind, happens in main too

Oh? If so, could you open an issue with the link to the failed job ?

**Comment by yuwata** [comment]
Hmmm. Actually I found
https://jenkins-systemd.apps.ocp.cloud.ci.centos.org/job/upstream-centos8/1932/artifact/systemd-centos-ci/artifacts_k40ra81y/testsuite-logs-upstream.ktu/systemd-networkd-tests.py_FAIL.log
Strange. I will take a look.

**Pull request merged**
