### PR TITLE
V253 stable batch

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by bluca** [comment]
```
Has header "/usr/include/efi/x86_64/efibind.h" : NO 

src/boot/efi/meson.build:40:16: ERROR: Problem encountered: gnu-efi support requested, but headers not found or efi arch is unknown
```

**Comment by keszybz** [comment]
Any idea what is the cause?
The only commit that could be related is 3168bda640fddfa6ca30cecea692dd6034c7714e.

**Comment by bluca** [comment]
> Any idea what is the cause? The only commit that could be related is [3168bda](https://github.com/systemd/systemd-stable/commit/3168bda640fddfa6ca30cecea692dd6034c7714e).

Uh how? That is a mkosi change, the failure is in packit, they don't share anything, no?

**Comment by keszybz** [comment]
No, I don't think it could be related. The failing command is:
```
+ /usr/bin/meson setup --buildtype=plain --prefix=/usr --libdir=/usr/lib64 --libexecdir=/usr/libexec --bindir=/usr/bin --sbindir=/usr/sbin --includedir=/usr/include --datadir=/usr/share --mandir=/usr/share/man --infodir=/usr/share/info --localedir=/usr/share/locale --sysconfdir=/etc --localstatedir=/var --sharedstatedir=/var/lib --wrap-mode=nodownload --auto-features=enabled . redhat-linux-build --werror -Dmode=release -Dsysvinit-path=/etc/rc.d/init.d -Drc-local=/etc/rc.d/rc.local '-Dntp-servers=0.fedora.pool.ntp.org 1.fedora.pool.ntp.org 2.fedora.pool.ntp.org 3.fedora.pool.ntp.org' -Ddns-servers= -Duser-path=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin -Dservice-watchdog= -Ddev-kvm-mode=0666 -Dkmod=true -Dxkbcommon=true -Dblkid=true -Dfdisk=true -Dseccomp=true -Dima=true -Dselinux=true -Dbpf-framework=true -Dapparmor=false -Dpolkit=true -Dxz=true -Dzlib=true -Dbzip2=true -Dlz4=true -Dzstd=true -Dpam=true -Dacl=true -Dsmack=true -Dopenssl=true -Dcryptolib=openssl -Dp11kit=true -Dgcrypt=false -Daudit=true -Delfutils=true -Dlibcryptsetup=true -Delfutils=true -Dpwquality=true -Dqrencode=true -Dgnutls=true -Dmicrohttpd=true -Dlibidn2=true -Dlibiptc=false -Dlibcurl=true -Dlibfido2=true -Defi=true -Dgnu-efi=true -Dtpm=true -Dtpm2=true -Dhwdb=true -Dsysusers=true -Dstandalone-binaries=true -Ddefault-kill-user-processes=false -Dfirst-boot-full-preset=true -Dtests=unsafe -Dinstall-tests=true -Dtty-gid=5 -Dusers-gid=100 -Dnobody-user=nobody -Dnobody-group=nobody -Dcompat-mutable-uid-boundaries=true -Dsplit-usr=false -Dsplit-bin=true -Db_lto=true -Db_ndebug=false -Dman=true -Dversion-tag=253-1.20230303103128124309.pr262.44.g6c327d74aa -Dshared-lib-tag=253-1.20230303103128124309.pr262.44.g6c327d74aa -Dfallback-hostname=localhost -Ddefault-dnssec=no -Ddefault-dns-over-tls=no -Ddefault-mdns=no -Ddefault-llmnr=resolve -Dstatus-unit-format-default=combined -Ddefault-timeout-sec=45 -Ddefault-user-timeout-sec=45 -Doomd=true -Dadm-gid=4 -Daudio-gid=63 -Dcdrom-gid=11 -Ddialout-gid=18 -Ddisk-gid=6 -Dinput-gid=104 -Dkmem-gid=9 -Dkvm-gid=36 -Dlp-gid=7 -Drender-gid=105 -Dsgx-gid=106 -Dtape-gid=33 -Dtty-gid=5 -Dusers-gid=100 -Dutmp-gid=22 -Dvideo-gid=39 -Dwheel-gid=10 -Dsystemd-journal-gid=190 -Dsystemd-network-uid=192 -Dsystemd-resolve-uid=193
```

**Comment by keszybz** [comment]
> > Any idea what is the cause? The only commit that could be related is [3168bda](https://github.com/systemd/systemd-stable/commit/3168bda640fddfa6ca30cecea692dd6034c7714e).
> 
> Uh how? That is a mkosi change, the failure is in packit, they don't share anything, no?

Yeah.

**Comment by bluca** [comment]
Isn't that just complaining that gnu-efi is not installed?

**Comment by bluca** [comment]
But it is installed. This is bizzarre... is it still `/usr/include/efi/x86_64/efibind.h` in Fedora?

**Comment by keszybz** [comment]
> But it is installed. This is bizzarre... is it still `/usr/include/efi/x86_64/efibind.h` in Fedora?

It's in updated rawhide compose. Let's ignore this for now.

**Comment by keszybz** [comment]
https://src.fedoraproject.org/rpms/gnu-efi/c/b3f0ac260b496aa99cf45a3d76cf5e315cd2a215?branch=rawhide

**Comment by bluca** [comment]
It's affecting main too, just checked the latest PRs, so yeah not a problem introduced here

**Comment by keszybz** [comment]
I can reproduce this with gnu-efi-devel-3.0.11-13.fc39.noarch. Note that gnu-efi-compat needs to be removed manually, it is not obsoleted.

**Comment by keszybz** [comment]
I'll merge this after lunch. Please don't merge here so that github doesn't mess up the hashes which are already referenced in https://github.com/systemd/systemd-stable/pull/263.

**Pull request merged**
