### PR TITLE
backports for v238

### PR DESCRIPTION
**Pull request by toanju**
networkd fixes cherry-picked from systemd/systemd@7ecf0c3, systemd/systemd@30226d2, systemd/systemd@cbff717

### CODE REVIEW

**Comment by yuwata** [comment]
Pleas use `-x` when cherry-picking. (https://github.com/systemd/systemd-stable/pull/39#issuecomment-462322788)

**Comment by toanju** [comment]
updated, thanks for the hint

**Comment by toanju** [comment]
ping @yuwata, anything else needed?

**Comment by keszybz** [comment]
LGTM.

**Pull request merged**
