### PR TITLE
backports up to 253-rc1

### PR DESCRIPTION
**Pull request by bluca**

### CODE REVIEW

**Comment by keszybz** [comment]
Meh, less than a 100.

**Comment by bluca** [comment]
with the pending headers and test fixes, that will be a round 100 backports!

**Comment by keszybz** [comment]
Hmm, I'm confused. Why are all those commits that do test and header cleanups included? Also all those commits that just add asserts?

**Comment by bluca** [comment]
> Hmm, I'm confused. Why are all those commits that do test and header cleanups included? Also all those commits that just add asserts?

Why not? They are obviously correct changes that don't break compat, and most importantly the less divergence the easier it is for other backports to apply cleanly, which reduces the amount of time it takes for us to do maintenance updates

**Comment by keszybz** [comment]
```
* 2edfbce914 (pr/247) test: handle Debian's /etc/default/locale in testsuite-74.firstboot.sh ???
* e595ec8cbd test: cover some interactive/error paths in firstboot  ???
* 3bed6ee48b test: re-enable skipped systemd-firstboot --locale-messages= test  ???
* 808adee473 test: make sure mount point exists in testsuite-64.sh 
* 02062d5301 boot: Use objcopy with arm64

* 53aeff11d5 sleep: fix memleak
* 75ae845584 sleep: reduce double logging and improve messages and comments a bit
* 11f69a60de sleep: do not abort if we try to query capacity of missing battery
The last one is useful, the other two are meh.
 
* 533fa63685 core: ensure init.scope is realized after drop-ins have been loaded
* fd11de1c27 test: bump the container spawn timeout to 60s
* 06ff6832fa test: bump the client-side timeout in sd-bus as well
* 455547fa20 machinectl: remove unnecessary initialization   ???
* 036e581e79 machinectl: also enable machines.target when enabling machines
* b7b79087a8 test: fix TEST-73-LOCALE on Debian
* 3cd137b017 shared/install: rework an assert to appease gcc-13
* 93f3f4d14d shared/install: rework InstallChange to always have .path set
* a69e58d6c7 test-unit-name: fix fd leak               ???
* 97ae316622 test-ndisc: fix memleak and fd leak       ???
* a776099bee core: mount namespaces: Remove auxiliary bind mounts directory after unit termination
* f8c48785ed network: do not enter failed state when received an invalid RA
* a3c28fa2f8 tree-wide: Use __func__ in asserts        ???
* a4eb2fdaad test-network: reprocess the loopback network interface
* b995f5197f test: bump D-Bus service start timeout if we run without accel
* 28298cf8bf coredump: use fstatvfs to check the available space             ???
This is not a fix. The new syscall may be rejected by selinux… It's always a risk, and I don't think we need this in -stable.

* fa80d1481a sd-dhcp-client: gracefully handle invalid ether type client ID
* c3de50f9ce network: fix memleak
* ec10b5900b mount: handle bind mount of file with non-existing target
* 12a99047b2 creds-util: merge the TPM2 detection for initrd
* fdc4b99a4b creds-util: do not try TPM2 if there is not support
* 2deb3a3cd8 creds-util: check for CAP_DAC_READ_SEARCH
* d917b90db2 gpt-auto: harden ESP/XBOOTLDR mounts with "noexec,nosuid,nodev"
* 62429fdaee busctl: fix introspecting DBus properties
* 68c188d278 test: explicitly create the /etc/init.d directory
* 051e0467ae network/l2tp: parse address or address type from correct string
* f9f806c1d6 network/l2tp: fix error code in log message
* 4442128a44 core/transaction: modernize to use cleanup attribute
* 447a34d6a0 manager: add one more assert()   ???
* cb66f57ffc import: use CURLOPT_PROTOCOLS_STR with libcurl >= 7.85.0
* b17ed3a160 import: use CURLINFO_SCHEME instead of CURLINFO_PROTOCOL
* 2806ac0a37 nspawn: guard acl_free() with a NULL check
* 1c21349f8a tmpfiles: avoid null free() for acl attributes
* ffe74b5264 sd-event: don't mistake USEC_INFINITY passed in for overflow
* e7ed4b84ba bootctl: Fix NULL pointer dereference
* 8e40016f13 resolved: disable SO_BINDTOIFINDEX hack for localhost IP addresses
* 206705f654 kernel-install: run depmod only if writeable
* 9db5e0e8f2 virt: fix container detection
* 424a832a1c resolvectl: remove duplicate ':' from output
* c6fd6e0b1c efi: skip Read() calls with zero sizes
* 774548fa42 resolved: downgrade inability to send varlink reply error message
* bdbdf8984c Revert "boot: Use EFI_BOOT_MANAGER_POLICY_PROTOCOL to connect console devices"
* 9fc2dcb2aa libsystemd-network: FTBS in c2x mode
* 0d42374498 basic: Fix incompatible type for arguments errors in C2X
* 150fd8aff0 basic: fix hosed return value in skip_session()
* 7ade396124 prioq: make prioq_reshuffle() void ???
* 8c7ee09c53 sysroot: Order systemd-fsck-root after systemd-makefs
* d58b11861e import-creds: don't try to import VM creds in a container
* 4e9169e41b macro: check existence of cleanup function before call it ???
* b7a6ce5447 resolve: fix enumerator name for DNS search domain
* b360cba745 fuzz: sort headers ???
* 47cdb195f0 units: allow systemd-userdbd to change process name
* c95944d0c0 sd-event: never pass negative errnos as signalfd to signalfd
* e25fe1f643 socket-proxyd: do not hardcode -1 in a check for fd validity  ???
* 5d881c1eff test: show and check almost all journal entries since the relevant command being invoked
* 24efca90ab test: suppress echo in monitor_check_rr()
* 93cf59cd79 swap: tell swapon to reinitialize swap if needed
* 0aa693adf8 locale-setup: avoid TOCTOU in reading locale.conf  ???
* e89212a0a9 locale-setup: make failure in stat() critical   ???
* 3879763da7 locale-setup: clear partially loaded context on failure
* 32ad675df3 locale-setup: split locale_context_load() into small pieces   ???
* 1bc01570b9 localed: avoid TOCTOU in loading config   ???
All those TOCTOUs purely theoretical.

* 45f2abb300 env-file: introduce parse_env_file_fd()      ???
* 1f11218b97 env-file: several cleanups       ???
* 5e093f1aa6 machine: propagate error from machine_new
* 8bd723b825 machine: use _cleanup_ in machine_new  ???
* 88b03a68f2 localed-util: use _cleanup_ harder   ???
* ae1a5fa5c8 busctl-introspect: use _cleanup_   ???
* 55986b485d ratelimit: drop use of goto    ???
* db57720653 core/namespace: indentation   ???
`_cleanup_` reworks are dangerous. If they fix a bug: sure, but just for the sake of cleanup: risky.

* 7e8fbdb277 treewide: drop "RUN_" from "RUN_WITH_UMASK" ???
* 8f6b6e9bd8 cryptsetup-fido2: Try all FIDO2 key slots when opening LUKS volume
* ea663ec5dd test: name_assign_type sysattr never exists for enumerated devices
* ab91103f54 mount-setup: don't need to mount /sys/fs/pstore if there is no ENABLE_PSTORE
* fb0e8cc71c resolve: add missing assertion   ???
* b3c30b8b85 resolve: shorten code a bit    ???
* dfb575eee2 localed: reload PID1 configuration after modifying /etc/locale.conf
* d22e60d947 sha256: external headers should be included with <>
That's just cleanup.

* d755f33561 core: pending_freezer_{message => invocation}     ???
* 16598d5ba2 core/sleep: set timeout for freeze/thaw operation to 1.5 seconds
* 1ba100aa07 test: wait for the monitoring service to become active
* 3dfa268068 core/slice: skip member units without realized cgroup during freeze or thaw
* e9cb2078a4 selinux-setup: minor modernizations   ???
* 9635c5c1c5 test-network: try to change MAC address more
* 8dd736bdc2 TEST-65: use [[ -v ]] more       ???
* 33cf80024a TEST-65: check cat-config operation in chroot   ???
* 495140353c boot: fix false maybe-uninitialized warning
* 8d00aec883 boot: cleanups for efivar_get() and friends         ???
* 218463244d test: update TEST-73-LOCALE to define several locale settings in initial PID1 environment
```

**Comment by keszybz** [comment]
> Why not? They are obviously correct changes that don't break compat, and most importantly the less divergence the easier it is for other backports to apply cleanly, which reduces the amount of time it takes for us to do maintenance updates

The problem is that each commit carries risk. I think it's fine to pull in cleanup commits if that allows a later commit that we care about to be applied cleanly — usually this is more likely to be done correctly then trying to reapply a patch with conflicts. But pulling in cleanup commits just for the sake of it is IMO wrong. We *do* make mistakes, even in cleanup commits, surprisingly often. And even benign changes that e.g. affect order of operations or what syscalls are called can cause problems, e.g. with MAC policies or container sandboxes or glibc variants. Similarly for tests — I think it's fine to pull in fixes for tests, so that e.g. we can run the tests and have more confidence, or to pull in tests for stuff that was backported, so that we can run the tests and have more confidence, but just pulling in tests for other stuff seems unnecessary.

**Comment by fbuihuu** [comment]
I second what @keszybz said, a stable release shouldn't include "cleanup" backports if there's no good reason to do so (ie if they really ease the backport of an actual fix and the risk of regression is low).

I encountered such case recently when reusing v249.14, which includes a bunch of reworks in udev (https://github.com/systemd/systemd-stable/commit/8ada2c1b5922110d961aa82e6d712f6eed696afe ... https://github.com/systemd/systemd-stable/commit/4a0c4d21ca03ffb37da3b5203988156644e13c5e) but none of the commits in the aforementioned range seemed to fix an issue (at least nothing where specified in their commit message). OTOH the risk of regressions is very high and one of the commit even change the format of the symlink directories (!).

I think we should be more careful.

**Comment by bluca** [comment]
I always prefer to backport obviously correct and compatible changes, especially cleanups that are tree-wide, as those pretty much guarantee merge conflicts for real bug fixes in the future.
But fine, I've dropped many (that are not necessary for subsequent fixes).

But I absolutely want to keep the test infrastructure as much in sync as it is possible (barring tests for new features of course), because that's the only sane way to keep the CI running in these branches. In previous stable branches this was not done, and the CI is useless there as it fails for unrelated reasons all over the place.
It is way safer to backport test changes, and being able to rely on the CI to validate bug fixes for the production components, than to avoid risks for the tests but have no CI coverage for these stable releases.

**Comment by keszybz** [comment]
Refactorings:
localed-util: use _cleanup_ harder
env-file: several cleanups
env-file: introduce parse_env_file_fd()
localed: avoid TOCTOU in loading config
locale-setup: *
macro: check existence of cleanup function before call it

New feature:
machinectl: also enable machines.target when enabling machines

Please drop those too.

The rest looks ok.

**Comment by bluca** [comment]
> Refactorings: localed-util: use _cleanup_ harder env-file: several cleanups env-file: introduce parse_env_file_fd() localed: avoid TOCTOU in loading config locale-setup: *

Those are all pre-reqs for the toctou fixes, they don't apply cleanly otherwise

> macro: check existence of cleanup function before call it
> New feature: machinectl: also enable machines.target when enabling machines

Sure, i thought it was a bug fix

**Comment by keszybz** [comment]
> > Refactorings: localed-util: use _cleanup_ harder env-file: several cleanups env-file: introduce parse_env_file_fd() localed: avoid TOCTOU in loading config locale-setup: *
> 
> Those are all pre-reqs for the toctou fixes, they don't apply cleanly otherwise

Yeah, but the toctou "fixes" are not fixes in a real sense. They are a way to write code in a theoretically more correct way, and also a bit nicer. But as described above, they are not without risk. So it's great to do those in a development branch, but generally they should not be included in a backport.

> > macro: check existence of cleanup function before call it
> > New feature: machinectl: also enable machines.target when enabling machines
> 
> Sure, i thought it was a bug fix

Well, it changes behaviour in a fairly significant way. If we have downstream reports that this fixes a issue — sure, let's take it. But without that, I don't think we should.

**Comment by keszybz** [comment]
Thanks!

**Pull request merged**
