### PR TITLE
v254 batch

### PR DESCRIPTION
**Pull request by bluca**

### CODE REVIEW

**Comment by mrc0mmand** [comment]
The CIFuzz issue looks relevant:
```
================== Job 2 exited with exit code 77 ============
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1337
INFO: Loaded 2 modules   (85508 inline 8-bit counters): 84422 [0x7fe6eeb075c0, 0x7fe6eeb1bf86), 1086 [0x60d718, 0x60db56), 
INFO: Loaded 2 PC tables (85508 PCs): 84422 [0x7fe6eeb1bf88,0x7fe6eec65be8), 1086 [0x60db58,0x611f38), 
INFO:     1581 files found in /github/workspace/cifuzz-corpus/fuzz-dhcp-server
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
INFO: seed corpus: files: 1581 min: 1b max: 4194303b total: 17290098b rss: 49Mb

=================================================================
==15262==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 62 byte(s) in 12 object(s) allocated from:
    #0 0x4a1e16 in malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:69:3
    #1 0x7fe6ee4e6367 in memdup_suffix0 /work/build/../../src/systemd/src/basic/alloc-util.c:33:15
    #2 0x7fe6ee5e1fc4 in make_cstring /work/build/../../src/systemd/src/basic/string-util.c:1351:21
    #3 0x4f4381 in dhcp_option_parse_string /work/build/../../src/systemd/src/libsystemd-network/dhcp-option.c:411:13
    #4 0x4e517a in parse_request /work/build/../../src/systemd/src/libsystemd-network/sd-dhcp-server.c:776:21
    #5 0x4f3ff8 in parse_options /work/build/../../src/systemd/src/libsystemd-network/dhcp-option.c:344:33
    #6 0x4f3904 in dhcp_option_parse /work/build/../../src/systemd/src/libsystemd-network/dhcp-option.c:377:21
    #7 0x4e2383 in dhcp_server_handle_message /work/build/../../src/systemd/src/libsystemd-network/sd-dhcp-server.c:1123:16
    #8 0x4ec637 in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/libsystemd-network/fuzz-dhcp-server.c:97:16
    #9 0x514ea3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #10 0x51468a in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:514:3
    #11 0x5164f4 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:826:7
    #12 0x516729 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:857:3
    #13 0x505d8f in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:912:6
    #14 0x52f3e2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #15 0x7fe6edbf4082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 87b331c034a6458c64ce09c03939e947212e18ce)

DEDUP_TOKEN: malloc--memdup_suffix0--make_cstring
SUMMARY: AddressSanitizer: 62 byte(s) leaked in 12 allocation(s).
```

**Comment by mrc0mmand** [comment]
Ah, and for the CentOS CI fail please backport 17ee59c9c922553a8cb4d54cb8ae415706c4feff, as without it `-fno-sanitize=function` is not passed to fuzz targets.

**Comment by mrc0mmand** [comment]
> The CIFuzz issue looks relevant:
> 
> ```
> ================== Job 2 exited with exit code 77 ============
> INFO: Running with entropic power schedule (0xFF, 100).
> INFO: Seed: 1337
> INFO: Loaded 2 modules   (85508 inline 8-bit counters): 84422 [0x7fe6eeb075c0, 0x7fe6eeb1bf86), 1086 [0x60d718, 0x60db56), 
> INFO: Loaded 2 PC tables (85508 PCs): 84422 [0x7fe6eeb1bf88,0x7fe6eec65be8), 1086 [0x60db58,0x611f38), 
> INFO:     1581 files found in /github/workspace/cifuzz-corpus/fuzz-dhcp-server
> INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
> INFO: seed corpus: files: 1581 min: 1b max: 4194303b total: 17290098b rss: 49Mb
> 
> =================================================================
> ==15262==ERROR: LeakSanitizer: detected memory leaks
> 
> Direct leak of 62 byte(s) in 12 object(s) allocated from:
>     #0 0x4a1e16 in malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:69:3
>     #1 0x7fe6ee4e6367 in memdup_suffix0 /work/build/../../src/systemd/src/basic/alloc-util.c:33:15
>     #2 0x7fe6ee5e1fc4 in make_cstring /work/build/../../src/systemd/src/basic/string-util.c:1351:21
>     #3 0x4f4381 in dhcp_option_parse_string /work/build/../../src/systemd/src/libsystemd-network/dhcp-option.c:411:13
>     #4 0x4e517a in parse_request /work/build/../../src/systemd/src/libsystemd-network/sd-dhcp-server.c:776:21
>     #5 0x4f3ff8 in parse_options /work/build/../../src/systemd/src/libsystemd-network/dhcp-option.c:344:33
>     #6 0x4f3904 in dhcp_option_parse /work/build/../../src/systemd/src/libsystemd-network/dhcp-option.c:377:21
>     #7 0x4e2383 in dhcp_server_handle_message /work/build/../../src/systemd/src/libsystemd-network/sd-dhcp-server.c:1123:16
>     #8 0x4ec637 in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/libsystemd-network/fuzz-dhcp-server.c:97:16
>     #9 0x514ea3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
>     #10 0x51468a in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:514:3
>     #11 0x5164f4 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:826:7
>     #12 0x516729 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:857:3
>     #13 0x505d8f in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:912:6
>     #14 0x52f3e2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
>     #15 0x7fe6edbf4082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 87b331c034a6458c64ce09c03939e947212e18ce)
> 
> DEDUP_TOKEN: malloc--memdup_suffix0--make_cstring
> SUMMARY: AddressSanitizer: 62 byte(s) leaked in 12 allocation(s).
> ```

This was probably fixed by 5a2f378362f2b16f8d837aec4c44532eed737a03.

**Comment by bluca** [comment]
Thanks, let's see if that fixes it

**Pull request merged**
