### PR TITLE
V254 stable batch

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by bluca** [comment]
I would skip [watchdog: Allow the watchdog to be disabled at runtime](https://github.com/systemd/systemd-stable/pull/311/commits/3c804509902621456ddc77cc0f483e6acafcd19a) as this area has been a bit flaky in the past (because it's very hard to test), so the potential for regression here is high and we don't have any test coverage

**Review by bluca — APPROVED** [review]
looks good, let's wait for the full CI run though

**Comment by keszybz** [comment]
I dropped "unit: make udev rules take precesence over tmpfiles"  because it's reverted in https://github.com/systemd/systemd/pull/28732/commits/41521e3a21fd266f553fe4f10a3ba97be41d1e55.

I'll drop the watchdog commit too.

**Comment by keszybz** [comment]
Somebody broke the internet:
```
+ git clone --quiet --depth=1 https://salsa.debian.org/ci-team/autopkgtest.git /tmp/autopkgtest
error: RPC failed; curl 16 Error in the HTTP2 framing layer
```

**Comment by bluca** [comment]
> Somebody broke the internet:
> 
> ```
> + git clone --quiet --depth=1 https://salsa.debian.org/ci-team/autopkgtest.git /tmp/autopkgtest
> error: RPC failed; curl 16 Error in the HTTP2 framing layer
> ```

yes it happens every now and then, I'll hit the retry buttons in 10 minutes or so

**Comment by keszybz** [comment]
The three jammy runners as still doing their thing, but it's been a couple of hours, so I'll merge this without waiting. Some other ubuntu-based CI passed, so I don't expect any issues to be uncovered.

**Pull request merged**
