### PR TITLE
V255 stable batch

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Backporting ec6c7bac5c92b26fc17ad165d2defc85da324391 should fix the Arch fails.

**Comment by keszybz** [comment]
mkosi/ci (centos, 8) failed wtih: Error: Unable to find a match: kernel-core-4.18.0-521.el8 kernel-modules-4.18.0-521.el8. Looks unrelated.

**Comment by mrc0mmand** [comment]
The failing Testing Farm job is also unrelated to this PR, but something I need to fix.

**Comment by bluca** [comment]
> mkosi/ci (fedora, rawhide) failed with: Error: Unable to get profile information [2]: No such file or directory ‣ "mkosi-chroot /work/postinst final" returned non-zero exit code 1.
> 
> Also unrelated.

Backporting this should fix it: https://github.com/systemd/systemd/pull/31043

**Comment by bluca** [comment]
This one is weird, did we miss some commit?

```
14:06:32 [    6.807993] testsuite-71.sh[391]: + systemctl stop systemd-hostnamed.service
14:06:32 [    6.856180] testsuite-71.sh[391]: + systemctl reset-failed systemd-hostnamed
14:06:32 [    6.867001] systemctl[465]: Failed to reset failed state of unit systemd-hostnamed.service: Unit systemd-hostnamed.service not loaded.
```

**Comment by keszybz** [comment]
> This one is weird, did we miss some commit?
> 
> ```
> 14:06:32 [    6.807993] testsuite-71.sh[391]: + systemctl stop systemd-hostnamed.service
> 14:06:32 [    6.856180] testsuite-71.sh[391]: + systemctl reset-failed systemd-hostnamed
> 14:06:32 [    6.867001] systemctl[465]: Failed to reset failed state of unit systemd-hostnamed.service: Unit systemd-hostnamed.service not loaded.
> ```

I dropped the commit that added this. `reset-failed` fails for units which are not loaded, so I'm not sure why it works in the tests. Let's try without this one patch, we probably don't need it.

**Comment by mrc0mmand** [comment]
> > This one is weird, did we miss some commit?
> > ```
> > 14:06:32 [    6.807993] testsuite-71.sh[391]: + systemctl stop systemd-hostnamed.service
> > 14:06:32 [    6.856180] testsuite-71.sh[391]: + systemctl reset-failed systemd-hostnamed
> > 14:06:32 [    6.867001] systemctl[465]: Failed to reset failed state of unit systemd-hostnamed.service: Unit systemd-hostnamed.service not loaded.
> > ```
> 
> I dropped the commit that added this. `reset-failed` fails for units which are not loaded, so I'm not sure why it works in the tests. Let's try without this one patch, we probably don't need it.

Heh, this actually works only thanks to the following commit from the same PR - 0a6598bb38a3ba4d627c105ee29582dcd2c118e3 - because it introduces a socket unit (`systemd-hostnamed.socket`), and that makes `reset-failed` happy for some reason:

```
# systemctl reset-failed systemd-hostnamed
Failed to reset failed state of unit systemd-hostnamed.service: Unit systemd-hostnamed.service not loaded.
# cp units/systemd-hostnamed.socket /usr/lib/systemd/system/
# systemctl daemon-reload
# systemctl reset-failed systemd-hostname
# systemctl reset-failed systemd-hostnamed && echo yipee
yipee
```

I still find the `reset-failed` behavior strange, but it's not something caused by this PR.

**Comment by mrc0mmand** [comment]
Also, for the Testing Farm job backporting https://github.com/systemd/systemd/pull/31062 (after it's merged) should help.

**Comment by mrc0mmand** [comment]
Aaaand for the C8S networkd fail 1ce2ffac6ca05bbeae0a4692a9a873c92be00a35 should help.

**Comment by bluca** [comment]
```
[ 3225.611123] testsuite-75.sh[44]: + systemctl start systemd-resolved.service
[ 3225.616996] systemd[1]: systemd-resolved.service: Start request repeated too quickly.
[ 3225.617055] systemd[1]: systemd-resolved.service: Failed with result 'start-limit-hit'.
```

That looks familiar, didn't you fix it in main @mrc0mmand ?

**Comment by mrc0mmand** [comment]
> ```
> [ 3225.611123] testsuite-75.sh[44]: + systemctl start systemd-resolved.service
> [ 3225.616996] systemd[1]: systemd-resolved.service: Start request repeated too quickly.
> [ 3225.617055] systemd[1]: systemd-resolved.service: Failed with result 'start-limit-hit'.
> ```
> 
> That looks familiar, didn't you fix it in main @mrc0mmand ?

Yup, that should be 68785c7d6a3fe27a57dac3028957910afcfe1718.

**Comment by bluca** [comment]
Any idea about this one?

```
19:51:07 [   37.734470] testsuite-17.sh[789]: + for _ in {1..40}
19:51:07 [   37.735359] testsuite-17.sh[974]: + coredumpctl --since '2024-01-23 19:50:37' --no-legend --no-pager
19:51:07 [   37.735828] testsuite-17.sh[975]: + grep /bin/udevadm
19:51:07 [   37.772479] coredumpctl[974]: No coredumps found.
```

**Comment by bluca** [comment]
@keszybz don't we also want 320ff932658fb1e3c2aeb1832ff6c10d755e5a56 ?

**Comment by yuwata** [comment]
The udev PRs are not necessary to be backported, as it _changes_ (rather than _fixes_) minor behavior on timeout, and hence the test was also updated in the PR.
Or, as already said, the whole patch set needs to be backported.
(Of course, some minor commits, e.g. logging, can be backported.)

**Comment by keszybz** [comment]
> @keszybz don't we also want [320ff93](https://github.com/systemd/systemd-stable/commit/320ff932658fb1e3c2aeb1832ff6c10d755e5a56) ?

Thanks. It wasn't merged yet when I was doing this and I forgot about it.

**Comment by mrc0mmand** [comment]
As for the TEST-17-UDEV fail, I'd just ignore it for this batch. I'd like to look into it more, which might take some time, and as said before it's not caused by this patchset, since it fails with _fresh_ v255 as well.

**Comment by bluca** [comment]
Tests are ran by consumers though, we do full runs now in Debian for example, so they shouldn't fail, can't we skip the subtest in this branch?

**Comment by keszybz** [comment]
> Tests are ran by consumers though, we do full runs now in Debian for example, so they shouldn't fail, can't we skip the subtest in this branch?

If the test failures were caused by the patches in this PR, then it would be reasonable to fix them. But I don't think we should backport two fairly big pull requests to fix failures *not* caused by the patches here. Also, I don't think we should suppress tests which are actually failing for legitimate reasons. This is something to do downstream.

**Comment by keszybz** [comment]
Franta pushed the commit while I was typing this. Let's run the CI with the commit. The decision whether to include it in the tag can be made later.

**Comment by keszybz** [comment]
Franta pushed the commit while I was typing this. Let's run the CI with the commit. The decision whether to include it in the tag can be made later.

**Comment by keszybz** [comment]
Franta pushed the commit while I was typing this. Let's run the CI with the commit. The decision whether to include it in the tag can be made later.

**Comment by mrc0mmand** [comment]
I found out what's going on, so I dropped the original commit that skipped the test and replaced it with a new one that makes the test happy (together with some explanation of what's going on). The commit is needed only in v255-stable (and potentially older stable releases), as after systemd/systemd#30532 the test no longer checks for coredumps, so the commit is no longer necessary.

**Comment by mrc0mmand** [comment]
The current Testing Farm fail is unrelated (it's a qemu segfault, not our fault, seen this one a couple of times already in other jobs).

**Comment by bluca** [comment]
Thanks - I think this is looking good now, anything else left to do?

**Comment by mrc0mmand** [comment]
> Thanks - I think this is looking good now, anything else left to do?

I'm not sure in what state the Ubuntu CI currently is, but if it's still fubar I'd go ahead and merge this, before the infra changes its mind.

**Comment by bluca** [comment]
It is, I was told yesterday that a fix for the status reporting is under review

**Pull request merged**
