### PR TITLE
bootctl: Make sure bootctl install returns 0 on success

### PR DESCRIPTION
**Pull request by DaanDeMeyer**

### CODE REVIEW

**Comment by eworm-de** [comment]
This does not exist in https://github.com/systemd/systemd repository, no?
Please open your pull request there.

**Comment by DaanDeMeyer** [comment]
@eworm-de The bug was fixed in https://github.com/systemd/systemd in https://github.com/systemd/systemd/commit/6e9165397faa1b546d367bdfc28dd4377a8f1d0a. Unfortunately, that commit adds a whole new feature that we don't want to backport which is why I'm opening this PR directly here instead of going via upstream.

**Comment by eworm-de** [comment]
Usually we use `cherry-pick -x` here. So we should at least mention the original commit id in commit message I guess.

**Comment by bluca** [comment]
Uhm this is targeted at 250-stable, but the regression is in 251? Can you rebase and switch the target branch?

**Pull request closed without merging**
