### PR TITLE
Backport 23009 to v250-stable

### PR DESCRIPTION
**Pull request by DaanDeMeyer**
Also some mkosi backports so we can build images and the tests pass.

Fixes https://github.com/systemd/systemd/issues/23961.

### CODE REVIEW

**Comment by yuwata** [comment]
Please use `-x` option when cherry-pick commits.

**Comment by DaanDeMeyer** [comment]
The first 3 commits had conflicts so I don't think it makes a difference there whether I use -x or not since -x only appends the message if there are no conflicts.

Fixed the last 2 commits

**Comment by yuwata** [comment]
> The first 3 commits had conflicts so I don't think it makes a difference there whether I use -x or not since -x only appends the message if there are no conflicts.

Then, how about to comment the original commit hash? E.g. "Based on the commit xxxxxxxx."

**Comment by DaanDeMeyer** [comment]
@yuwata Re-applied all commits with cherry-pick-x PTAL

**Comment by yuwata** [comment]
Still two mkosi CIs are red, but now the state should be better than previous. Let's address them later if necessary. Merging.

**Pull request merged**
