### PR TITLE
v252.5 in spe

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by bluca** [comment]
given bf976c6a8ed935574ef9790d01941d93937d80bc is in the list, I'd also pick 645063d1bb309137f884d9c9f01d2b7d01ab2ca8 as it's obviously correct and the static analysis warning applies just the same

**Comment by keszybz** [comment]
rpm-build builds are failing with `meson.build:3:0: ERROR: Unknown options: "default-timeout-sec, default-user-timeout-sec"`.

**Comment by keszybz** [comment]
Done.

**Comment by bluca** [comment]
> rpm-build builds are failing with `meson.build:3:0: ERROR: Unknown options: "default-timeout-sec, default-user-timeout-sec"`.

we could add a stable-specif change to drop those? like 61f5710d0bfd8f522af6f8eef399a851509946e2

**Comment by bluca** [comment]
added now, if packit passes I'll merge as the rest already was green

**Pull request merged**
