### PR TITLE
V251 stable batch

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by bluca** [comment]
```
08:53:30 FAILED TASKS:
08:53:30 -------------
08:53:30 TEST-46-HOMED
```

This is a regression since the last v251 release

**Comment by keszybz** [comment]
```
Mar 31 09:52:01 H systemd-homework[739]: Using automatic default storage of 'luks'.
Mar 31 09:52:01 H systemd-homework[739]: Allocating image file completed.
Mar 31 09:52:01 H systemd-homework[739]: Writing of partition table completed.
Mar 31 09:52:01 H systemd-homework[739]: Setting up loopback device /dev/loop0 completed.
Mar 31 09:52:01 H kernel: loop0: detected capacity change from 0 to 555008
Mar 31 09:52:02 H kernel: operation not supported error, dev loop0, sector 0 op 0x9:(WRITE_ZEROES) flags 0x8000800 phys_seg 0 prio class 2
Mar 31 09:52:02 H kernel: operation not supported error, dev loop0, sector 2048 op 0x9:(WRITE_ZEROES) flags 0x8000800 phys_seg 0 prio class 2
Mar 31 09:52:02 H kernel: operation not supported error, dev loop0, sector 4096 op 0x9:(WRITE_ZEROES) flags 0x8000800 phys_seg 0 prio class 2
Mar 31 09:52:02 H kernel: operation not supported error, dev loop0, sector 6144 op 0x9:(WRITE_ZEROES) flags 0x8000800 phys_seg 0 prio class 2
Mar 31 09:52:02 H kernel: operation not supported error, dev loop0, sector 8192 op 0x9:(WRITE_ZEROES) flags 0x8000800 phys_seg 0 prio class 2
Mar 31 09:52:02 H kernel: operation not supported error, dev loop0, sector 10240 op 0x9:(WRITE_ZEROES) flags 0x8000800 phys_seg 0 prio class 2
Mar 31 09:52:02 H kernel: operation not supported error, dev loop0, sector 12288 op 0x9:(WRITE_ZEROES) flags 0x8000800 phys_seg 0 prio class 2
Mar 31 09:52:02 H kernel: operation not supported error, dev loop0, sector 14336 op 0x9:(WRITE_ZEROES) flags 0x8000800 phys_seg 0 prio class 2
Mar 31 09:52:02 H kernel: operation not supported error, dev loop0, sector 16384 op 0x9:(WRITE_ZEROES) flags 0x8000800 phys_seg 0 prio class 2
Mar 31 09:52:02 H kernel: operation not supported error, dev loop0, sector 18432 op 0x9:(WRITE_ZEROES) flags 0x8000800 phys_seg 0 prio class 2
Mar 31 09:52:02 H systemd-homework[739]: LUKS formatting completed.
Mar 31 09:52:04 H systemd-homework[739]: Writing password to LUKS keyslot 0 completed.
...
Mar 31 09:52:16 H kernel: blk_print_req_error: 7 callbacks suppressed
Mar 31 09:52:16 H kernel: I/O error, dev loop0, sector 0 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 2
```

Dunno, it seems to wait for some state change that never appears. I don't think this is related to any of those patches, they don't touch src/home or any relevant tests.

**Comment by mrc0mmand** [comment]
> ```
> Mar 31 09:52:01 H systemd-homework[739]: Using automatic default storage of 'luks'.
> Mar 31 09:52:01 H systemd-homework[739]: Allocating image file completed.
> Mar 31 09:52:01 H systemd-homework[739]: Writing of partition table completed.
> Mar 31 09:52:01 H systemd-homework[739]: Setting up loopback device /dev/loop0 completed.
> Mar 31 09:52:01 H kernel: loop0: detected capacity change from 0 to 555008
> Mar 31 09:52:02 H kernel: operation not supported error, dev loop0, sector 0 op 0x9:(WRITE_ZEROES) flags 0x8000800 phys_seg 0 prio class 2
> Mar 31 09:52:02 H kernel: operation not supported error, dev loop0, sector 2048 op 0x9:(WRITE_ZEROES) flags 0x8000800 phys_seg 0 prio class 2
> Mar 31 09:52:02 H kernel: operation not supported error, dev loop0, sector 4096 op 0x9:(WRITE_ZEROES) flags 0x8000800 phys_seg 0 prio class 2
> Mar 31 09:52:02 H kernel: operation not supported error, dev loop0, sector 6144 op 0x9:(WRITE_ZEROES) flags 0x8000800 phys_seg 0 prio class 2
> Mar 31 09:52:02 H kernel: operation not supported error, dev loop0, sector 8192 op 0x9:(WRITE_ZEROES) flags 0x8000800 phys_seg 0 prio class 2
> Mar 31 09:52:02 H kernel: operation not supported error, dev loop0, sector 10240 op 0x9:(WRITE_ZEROES) flags 0x8000800 phys_seg 0 prio class 2
> Mar 31 09:52:02 H kernel: operation not supported error, dev loop0, sector 12288 op 0x9:(WRITE_ZEROES) flags 0x8000800 phys_seg 0 prio class 2
> Mar 31 09:52:02 H kernel: operation not supported error, dev loop0, sector 14336 op 0x9:(WRITE_ZEROES) flags 0x8000800 phys_seg 0 prio class 2
> Mar 31 09:52:02 H kernel: operation not supported error, dev loop0, sector 16384 op 0x9:(WRITE_ZEROES) flags 0x8000800 phys_seg 0 prio class 2
> Mar 31 09:52:02 H kernel: operation not supported error, dev loop0, sector 18432 op 0x9:(WRITE_ZEROES) flags 0x8000800 phys_seg 0 prio class 2
> Mar 31 09:52:02 H systemd-homework[739]: LUKS formatting completed.
> Mar 31 09:52:04 H systemd-homework[739]: Writing password to LUKS keyslot 0 completed.
> ...
> Mar 31 09:52:16 H kernel: blk_print_req_error: 7 callbacks suppressed
> Mar 31 09:52:16 H kernel: I/O error, dev loop0, sector 0 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 2
> ```
> 
> Dunno, it seems to wait for some state change that never appears. I don't think this is related to any of those patches, they don't touch src/home or any relevant tests.

This one is a known race, but other tries fail with:

```
[  138.556144] testsuite-46.sh[1598]: /usr/lib/systemd/tests/testdata/units/testsuite-46.sh: line 224: jq: command not found
```

so backporting 7906b790e4549d71087a6a94354ba02c2f1b6fa2 (or a part of it) should fix this.

**Comment by bluca** [comment]
How about this one, is it a known issue @mrc0mmand ?

```
Assertion 'sched_setscheduler(0, SCHED_FIFO, &(struct sched_param) { .sched_priority = 1 }) >= 0' failed at src/test/test-seccomp.c:560, function test_restrict_realtime(). Aborting.
```

**Comment by mrc0mmand** [comment]
> How about this one, is it a known issue @mrc0mmand ?
> 
> ```
> Assertion 'sched_setscheduler(0, SCHED_FIFO, &(struct sched_param) { .sched_priority = 1 }) >= 0' failed at src/test/test-seccomp.c:560, function test_restrict_realtime(). Aborting.
> ```

That sounds like https://github.com/systemd/systemd/issues/17078 which was fixed/worked around in https://github.com/systemd/systemd/pull/24645, so yeah.

**Comment by keszybz** [comment]
I'll go ahead and merge this. I don't think it makes sense to spend more time to figure out all the test failures.

**Comment by keszybz** [comment]
@bluca, @mrc0mmand thanks!

**Pull request merged**
