### PR TITLE
Prep for v254.7

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by keszybz** [comment]
mkosi/ci (opensuse): I plead not guilty:
```
Problem: busybox-diffutils-1.36.1-30.2.noarch conflicts with diffutils provided by diffutils-3.10-1.5.x86_64
 Solution 1: deinstallation of busybox-diffutils-1.36.1-30.2.noarch
 Solution 2: do not install diffutils-3.10-1.5.x86_64
```

**Comment by bluca** [comment]
```
14:21:46     archlinux_systemd_ci: + meson /systemd-meson-build --werror '-Dc_args=-fno-omit-frame-pointer -ftrapv' -Ddebug=true --optimization=g -Dlog-trace=true -Dfexecve=true -Dslow-tests=true -Dfuzz-tests=true -Dtests=unsafe -Dinstall-tests=true -Ddbuspolicydir=/usr/share/dbus-1/system.d -Dlocalegen-path=/usr/bin/locale-gen '' -Dman=true -Dhtml=true
14:21:46     archlinux_systemd_ci: usage: meson [-h]
14:21:46     archlinux_systemd_ci:              {setup,configure,dist,install,introspect,init,test,wrap,subprojects,rewrite,compile,devenv,env2mfile,help}
14:21:46     archlinux_systemd_ci:              ...
14:21:46     archlinux_systemd_ci: meson: error: unrecognized arguments:
```

**Comment by keszybz** [comment]
> ```
> 14:21:46     archlinux_systemd_ci: + meson /systemd-meson-build --werror '-Dc_args=-fno-omit-frame-pointer -ftrapv' -Ddebug=true --optimization=g -Dlog-trace=true -Dfexecve=true -Dslow-tests=true -Dfuzz-tests=true -Dtests=unsafe -Dinstall-tests=true -Ddbuspolicydir=/usr/share/dbus-1/system.d -Dlocalegen-path=/usr/bin/locale-gen '' -Dman=true -Dhtml=true
> 14:21:46     archlinux_systemd_ci: usage: meson [-h]
> 14:21:46     archlinux_systemd_ci:              {setup,configure,dist,install,introspect,init,test,wrap,subprojects,rewrite,compile,devenv,env2mfile,help}
> 14:21:46     archlinux_systemd_ci:              ...
> 14:21:46     archlinux_systemd_ci: meson: error: unrecognized arguments:
> ```

Something is passing an empty argument to `meson`, and it doesn't like that.
But I don't think this can be caused by any of the commit in this series: the only one that touches `meson.build` is 22eb30e42e, but that doesn't seem relevant. Directory `.github` and the test setup is not modified.

a9ead31c8b analyze: do not prepend the current working directory to SYSTEMD_UNIT_PATH needlessly was messed up during cherry-pick. (It seems the chunk applies cleanly, but in a wrong place.)  I dropped it from the list.

**Comment by mrc0mmand** [comment]
> > ```
> > 14:21:46     archlinux_systemd_ci: + meson /systemd-meson-build --werror '-Dc_args=-fno-omit-frame-pointer -ftrapv' -Ddebug=true --optimization=g -Dlog-trace=true -Dfexecve=true -Dslow-tests=true -Dfuzz-tests=true -Dtests=unsafe -Dinstall-tests=true -Ddbuspolicydir=/usr/share/dbus-1/system.d -Dlocalegen-path=/usr/bin/locale-gen '' -Dman=true -Dhtml=true
> > 14:21:46     archlinux_systemd_ci: usage: meson [-h]
> > 14:21:46     archlinux_systemd_ci:              {setup,configure,dist,install,introspect,init,test,wrap,subprojects,rewrite,compile,devenv,env2mfile,help}
> > 14:21:46     archlinux_systemd_ci:              ...
> > 14:21:46     archlinux_systemd_ci: meson: error: unrecognized arguments:
> > ```
> 
> Something is passing an empty argument to `meson`, and it doesn't like that. But I don't think this can be caused by any of the commit in this series: the only one that touches `meson.build` is [22eb30e](https://github.com/systemd/systemd-stable/commit/22eb30e42e8ef12715c37f2bf5475609a9193229), but that doesn't seem relevant. Directory `.github` and the test setup is not modified.
> 
> [a9ead31](https://github.com/systemd/systemd-stable/commit/a9ead31c8be62db4b90792624e0a329dece8d825) analyze: do not prepend the current working directory to SYSTEMD_UNIT_PATH needlessly was messed up during cherry-pick. (It seems the chunk applies cleanly, but in a wrong place.) I dropped it from the list.

Ah, that's a change on CentOS CI's side, lemme fix that.

**Comment by mrc0mmand** [comment]
Welp, apparently not, the cloud broke again, *sigh*...

**Comment by keszybz** [comment]
mkosi / ci (opensuse, tumbleweed) failed as before.

**Pull request merged**
