### PR TITLE
V255 stable batch

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Review by bluca — APPROVED** [review]
list looks fine, let's see if the CI agrees

**Comment by bluca** [comment]
`Outdated pages: org.freedesktop.resolve1.xml`

**Comment by bluca** [comment]
`lxml.etree.XMLSyntaxError: Entity 'fedora_cloud_release' not defined, line 1065, column 176`

**Comment by keszybz** [comment]
```
03:41:41 ======================================================================
03:41:41 FAIL: test_sysctl (__main__.NetworkdNetworkTests.test_sysctl)
03:41:41 ----------------------------------------------------------------------
03:41:41 Traceback (most recent call last):
03:41:41   File "/build/test/test-network/systemd-networkd-tests.py", line 3598, in test_sysctl
03:41:41     self.check_ipv4_sysctl_attr('dummy98', 'rp_filter', '0')
03:41:41   File "/build/test/test-network/systemd-networkd-tests.py", line 892, in check_ipv4_sysctl_attr
03:41:41     self.assertEqual(read_ipv4_sysctl_attr(link, attribute), expected)
03:41:41 AssertionError: '2' != '0'
03:41:41 - 2
03:41:41 + 0
```
There are three commits in the series which touch `src/network` or `test/test-network`, but I don't think they're related to this.

**Pull request merged**
