### PR TITLE
v255 tests/repro fixes

### PR DESCRIPTION
**Pull request by bluca**

### CODE REVIEW

**Comment by bluca** [comment]
@mrc0mmand any idea why the udev unit test is failing here and not in main? Are we missing something?

**Comment by mrc0mmand** [comment]
> @mrc0mmand any idea why the udev unit test is failing here and not in main? Are we missing something?

Maybe 56cdf81a72795e15ff7751f62d421b1505b82846?

**Comment by mrc0mmand** [comment]
Also, the Rawhide CI fails because it's missing https://github.com/systemd/systemd/pull/31209 - do we want to backport this as well?

**Comment by bluca** [comment]
> Also, the Rawhide CI fails because it's missing [systemd/systemd#31209](https://github.com/systemd/systemd/pull/31209) - do we want to backport this as well?

That seems too risky to backport, so I've skipped the two failing tests instead

**Comment by bluca** [comment]
@mrc0mmand is this also due to the lack of clone_into_cgroup?

```
[  825.947962] testsuite-04.sh[10337]: + journalctl --sync
[  825.952956] testsuite-04.sh[10920]: ++ journalctl -n 1 -p info -o cat --unit=test-cursor-9960.service '--after-cursor=s=e31c5fc2403b4ebbbe437f69a17d7ea8;i=12c00;b=1ae2cc1e5bd54c0abba9f10e7fb1ad21;m=313a9a91;t=6112e8cb4e988;x=e7754d93d2d8e13a' _PID=1
[  825.963712] testsuite-04.sh[10337]: + [[ Starting test-cursor-9960.service - /usr/bin/bash -xec "echo hello; echo world"... =~ ^Starting  ]]
[  825.963861] testsuite-04.sh[10921]: ++ journalctl -n 1 -p info -o cat --unit=test-cursor-9960.service '--after-cursor=s=e31c5fc2403b4ebbbe437f69a17d7ea8;i=12c00;b=1ae2cc1e5bd54c0abba9f10e7fb1ad21;m=313a9a91;t=6112e8cb4e988;x=e7754d93d2d8e13a' --reverse
[  825.963980] testsuite-04.sh[10337]: + [[ -z '' ]]
[  825.963980] testsuite-04.sh[10337]: + diff /dev/fd/63 -
[  825.964094] testsuite-04.sh[10922]: ++ journalctl --cursor-file=/tmp/tmp.pwcz31Pd1y -p info -o cat _SYSTEMD_UNIT=test-cursor-9960.service
[  825.965973] testsuite-04.sh[10923]: 0a1,4
[  825.965973] testsuite-04.sh[10923]: > + echo hello
[  825.965973] testsuite-04.sh[10923]: > hello
[  825.965973] testsuite-04.sh[10923]: > + echo world
[  825.965973] testsuite-04.sh[10923]: > world
[  825.966585] testsuite-04.sh[44]: + echo 'Subtest /usr/lib/systemd/tests/testdata/units/testsuite-04.journal.sh failed'
```

**Comment by mrc0mmand** [comment]
Yeah:

```
$ journalctl --file TEST-04-JOURNAL.journal -o short-monotonic MESSAGE=hello -o export
...
__CURSOR=s=b4a6e16f0abe4978bc3d15b7b1840e37;i=c04;b=1ae2cc1e5bd54c0abba9f10e7fb1ad21;m=313ae4ce;t=6112e8cb533c5;x=d6385788b7fae72e
__REALTIME_TIMESTAMP=1707741487117253
__MONOTONIC_TIMESTAMP=825943246
__SEQNUM=3076
__SEQNUM_ID=b4a6e16f0abe4978bc3d15b7b1840e37
_BOOT_ID=1ae2cc1e5bd54c0abba9f10e7fb1ad21
SYSLOG_FACILITY=3
PRIORITY=6
_UID=0
_GID=0
_SELINUX_CONTEXT=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
_MACHINE_ID=fbf954fa70684fa8b42c7c768a25ac28
_HOSTNAME=H
_RUNTIME_SCOPE=system
_CAP_EFFECTIVE=fdecafff
_SYSTEMD_CGROUP=/init.scope
_SYSTEMD_UNIT=init.scope
_SYSTEMD_SLICE=-.slice
_TRANSPORT=stdout
_EXE=/usr/lib/systemd/systemd-executor
MESSAGE=hello
_PID=10916
_COMM=(bash)
_CMDLINE="(bash)"
_STREAM_ID=993531fa24f74bee9e4b7cc3cb855cab
SYSLOG_IDENTIFIER=bash
```

**Pull request merged**
