### PR TITLE
252.1

### PR DESCRIPTION
**Pull request by bluca**

### CODE REVIEW

**Comment by mrc0mmand** [comment]
59ab79a73d030a49bfdffd85897b6b30a2b132c5 should make the TEST-73 happy.

**Comment by bluca** [comment]
> [59ab79a](https://github.com/systemd/systemd-stable/commit/59ab79a73d030a49bfdffd85897b6b30a2b132c5) should make the TEST-73 happy.

mmh but it's already in v252?

**Comment by bluca** [comment]
maybe https://github.com/systemd/systemd/pull/25279 ?

**Comment by mrc0mmand** [comment]
> maybe [systemd/systemd#25279](https://github.com/systemd/systemd/pull/25279) ?

Ugh, yeah, you're right, [59ab79a](https://github.com/systemd/systemd-stable/commit/59ab79a73d030a49bfdffd85897b6b30a2b132c5) is not even TEST-73. Time to grab another coffee...

**Comment by mrc0mmand** [comment]
The ASan fail is unrelated (https://github.com/systemd/systemd/issues/24147).

**Pull request merged**
