### PR TITLE
[v248] systemd-networkd-wait-online: wait for specific address family

### PR DESCRIPTION
**Pull request by vteratipally**
Backported from https://github.com/systemd/systemd/pull/19069

### CODE REVIEW

**Comment by bsdnet** [comment]
After v246 introduces the feature either IPv4 or IPv6 is configured, the link is marked as configured. This is becoming an issue in environment where either IPv4 or IPv6 delay some significant time. Backporting to v248 or v249 will give distro's choice to make systemd behave backwards compatible, and each distro do not maintain those patches separately.

**Comment by yuwata** [comment]
Sorry, the commits implement a new feature. Basically, we do not backport anything about new features, but only bug fixes.
Of course, I understand the feature solves some issues, but these are not caused by a bug in networkd or networkd-wait-online.

Please contact to your distro to apply these commits into v248 or any older releases.

**Comment by vteratipally** [comment]
Thank you for the feedback.

**Pull request closed without merging**
