### PR TITLE
v251.8

### PR DESCRIPTION
**Pull request by bluca**

### CODE REVIEW

**Comment by bluca** [comment]
@mrc0mmand @keszybz any idea what's missing for the failing tests? We really should get these stable branches to work, otherwise we risk silly regressions

**Comment by mrc0mmand** [comment]
> @mrc0mmand @keszybz any idea what's missing for the failing tests? We really should get these stable branches to work, otherwise we risk silly regressions



For the C8S fails: cde09b07dfdc132a31672693c037bfc0b5879331 and 12ee072db571d5d3aca37fbf9b9261441ac9aeff
For ASan fails: 3917534d620c2b358a196431b9e2593218ba1ac9
For Build test: dfe7cfe4fbd4d2de99a8e97919dd5f7cdef1a1c5
For Linter: at least 6c0259e50203a9a8851cd4bc6f8e8f8f21361049 and 9e03f48d21871bbca5efbfd26b67aca12265a618

**Comment by mrc0mmand** [comment]
Ah, another unused variable. I remember this game of whack-a-mole, we probably need the remaining commits from https://github.com/systemd/systemd/pull/24379/commits.

**Comment by bluca** [comment]
> Ah, another unused variable. I remember this game of whack-a-mole - we probably need the remaining commits from https://github.com/systemd/systemd/pull/24379/commits.

that's my favourite game, let me fetch my sledgehammer

**Comment by mrc0mmand** [comment]
Ugh, we need 8fec14a7d397f52b93024bf3417de8f77b0d85e6 for TEST-70-TPM2 as well to avoid the OOM stuff.

For C8S I missed one patch (since the test was renamed) - 0f1f5629747011d0401730ce81c955ec1d430e3d - but it applies cleanly, thanks to git being clever in this case.

Also, since you backported [e090b0f](https://github.com/systemd/systemd-stable/pull/227/commits/e090b0f5c58700f8dcf9f63a2e8c080d10610659) we'll need to backport 2cfb790391958ada34284290af1f9ab863a515c7 as well, otherwise a couple of tests will keep dying with segfault.

With this the tests should, hopefully, pass.

**Comment by mrc0mmand** [comment]
Almost there! It looks we're missing just the ASan related follow-ups: 94850fb956458703e0c6e0bee7f482aa41a47e9e, fdb70dd9222219307ca53662e789fc9304ca3616, and 5ad15138458b4f2957bd9d2bc2c8e3c9afe99337. Let's hope it's the last batch of missing patches.

**Comment by mrc0mmand** [comment]
@bluca everything's green, *quickly, merge it before it changes its mind!*

**Comment by bluca** [comment]
> @bluca everything's green, _quickly, merge it before it changes its mind!_

woop woop great job, thank you!

**Comment by thesamesam** [comment]
Could you push the tag please? Thanks!

**Comment by mrc0mmand** [comment]
> Could you push the tag please? Thanks!

https://github.com/systemd/systemd-stable/releases/tag/v251.8

**Pull request merged**
