### PR TITLE
v252 backports

### PR DESCRIPTION
**Pull request by eworm-de**

### CODE REVIEW

**Comment by bluca** [comment]
This is a new option, and we don't add new options to stable releases usually?

**Comment by eworm-de** [comment]
The merge request from main branch has the `needs-stable-backport` label set. But I can understand your concern and I am fine to wait for v253.

**Comment by boudekerk** [comment]
I know this his been debated at length, in #25269. But most people seem to believe it to be a breaking change to an existing option, which would warrant a backport IMO. The new option being introduced is part of the fix. i.e. the original functionality is restored, but the new (previously breaking) behaviour is not removed, but instead being made available in a new option.

As the new option is part of the "fix", wouldn't a backport be appropriate regardless?

**Comment by keszybz** [comment]
Pfff, this is tough. But I think we're better off merging this. For people upgrading from v251, this is clear: we maintain compatibility. People who were already on v252 and adjusted to the new behaviour would see a disruption. But I think that the amount of such people will be small. There were many people who commented in #25269, so the change in v252 was clearly causing problems.

**Pull request merged**
