### PR TITLE
[v249] backports of fixes till 2022/03/09

### PR DESCRIPTION
**Pull request by bluca**

### CODE REVIEW

**Comment by bluca** [comment]
```
21:36:45 D: Installing /bin/df
21:36:45 F: Failed to install dhclient
```

@mrc0mmand what do we need to make this work?

**Comment by mrc0mmand** [comment]
> ```
> 21:36:45 D: Installing /bin/df
> 21:36:45 F: Failed to install dhclient
> ```
> 
> @mrc0mmand what do we need to make this work?

Ah, I see, `dhclient` is part of the `$DEBUGTOOLS` array and since f7d47cc86264cd86f9f81962bfa1757e64b664a4 the tools from that array are optional. So either backport that commit or I can install dhclient in the C8S jobs.

**Comment by mrc0mmand** [comment]
> > ```
> > 21:36:45 D: Installing /bin/df
> > 21:36:45 F: Failed to install dhclient
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @mrc0mmand what do we need to make this work?
> 
> Ah, I see, `dhclient` is part of the `$DEBUGTOOLS` array and since [f7d47cc](https://github.com/systemd/systemd-stable/commit/f7d47cc86264cd86f9f81962bfa1757e64b664a4) the tools from that array are optional. So either backport that commit or I can install dhclient in the C8S jobs.

And a second "ah, I see", we dropped the `dhclient` dep on dracut in RHEL/CentOS 8, since we moved to NetworkManager, so that might be a reason why it's no longer present on the test machines. So I guess I'll go ahead and install it there anyway. Will push a patch shortly and restart the job.

**Comment by bluca** [comment]
I can cherry-pick that commit, not a problem - thanks

**Comment by mrc0mmand** [comment]
Looks like the job got past the "problematic" point, so it should be fine. As for the pull request labeler - the error is a bit cryptic, but I guess the issue there is that this repo doesn't have the necessary labels for it to work properly - not an actual issue though.

**Comment by bluca** [comment]
ok I'll avoid the cherry-pick then - thanks! Yeah I'm not worried about the labeler, in fact we should probably just disable it here

**Comment by bluca** [comment]
```
23:06:54 # /run/systemd/system/systemd-udevd.service.d/00-override.conf
23:06:54 [Service]
23:06:54 ExecStart=
23:06:54 ExecStart=!!/usr/lib/systemd/systemd-udevd
23:06:54 test_altname (__main__.NetworkctlTests) ... Found link 41
23:06:54 Found link 34
23:06:54 Found link 33
23:06:54 Found link 30
23:06:54 Found link 29
23:06:54 Found link 28
23:06:54 Found link 27
23:06:54 Found link 24
23:06:54 Found link 23
23:06:54 Found link 22
23:06:54 Found link 21
23:06:54 Found link 20
23:06:54 Found link 19
23:06:54 Found link 18
23:06:54 Found link 17
23:06:54 Found link 16
23:06:54 Found link 15
23:06:54 Found link 14
23:06:54 Found link 13
23:06:54 Found link 12
23:06:54 Found link 9
23:06:54 Found link 8
23:06:54 Found link 7
23:06:54 Found link 6
23:06:54 Found link 5
23:06:54 Found link 4
23:06:54 Found link 3
23:06:54 Found link 2
23:06:54 Found link 1
23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
23:06:54 Timeout occurred while waiting for network connectivity.
```

```
23:06:55 ======================================================================
23:06:55 ERROR: test_altname (__main__.NetworkctlTests)
23:06:55 ----------------------------------------------------------------------
23:06:55 Traceback (most recent call last):
23:06:55   File "./test/test-network/systemd-networkd-tests.py", line 665, in test_altname
23:06:55     self.wait_online(['dummy98:degraded'])
23:06:55   File "./test/test-network/systemd-networkd-tests.py", line 602, in wait_online
23:06:55     check_output(*args, env=env)
23:06:55   File "./test/test-network/systemd-networkd-tests.py", line 50, in check_output
23:06:55     return subprocess.check_output(command, universal_newlines=True, **kwargs).rstrip()
23:06:55   File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
23:06:55     **kwargs).stdout
23:06:55   File "/usr/lib64/python3.6/subprocess.py", line 438, in run
23:06:55     output=stdout, stderr=stderr)
23:06:55 subprocess.CalledProcessError: Command '['/usr/lib/systemd/systemd-networkd-wait-online', '--timeout=20s', '--interface=dummy98:degraded']' returned non-zero exit status 1.
```

Any idea about this one?

**Comment by mrc0mmand** [comment]
> ```
> 23:06:54 # /run/systemd/system/systemd-udevd.service.d/00-override.conf
> 23:06:54 [Service]
> 23:06:54 ExecStart=
> 23:06:54 ExecStart=!!/usr/lib/systemd/systemd-udevd
> 23:06:54 test_altname (__main__.NetworkctlTests) ... Found link 41
> 23:06:54 Found link 34
> 23:06:54 Found link 33
> 23:06:54 Found link 30
> 23:06:54 Found link 29
> 23:06:54 Found link 28
> 23:06:54 Found link 27
> 23:06:54 Found link 24
> 23:06:54 Found link 23
> 23:06:54 Found link 22
> 23:06:54 Found link 21
> 23:06:54 Found link 20
> 23:06:54 Found link 19
> 23:06:54 Found link 18
> 23:06:54 Found link 17
> 23:06:54 Found link 16
> 23:06:54 Found link 15
> 23:06:54 Found link 14
> 23:06:54 Found link 13
> 23:06:54 Found link 12
> 23:06:54 Found link 9
> 23:06:54 Found link 8
> 23:06:54 Found link 7
> 23:06:54 Found link 6
> 23:06:54 Found link 5
> 23:06:54 Found link 4
> 23:06:54 Found link 3
> 23:06:54 Found link 2
> 23:06:54 Found link 1
> 23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
> 23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
> 23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
> 23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
> 23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
> 23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
> 23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
> 23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
> 23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
> 23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
> 23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
> 23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
> 23:06:54 dummy98: Operational state 'off' is not in range ['degraded':'routable']
> 23:06:54 Timeout occurred while waiting for network connectivity.
> ```
> 
> ```
> 23:06:55 ======================================================================
> 23:06:55 ERROR: test_altname (__main__.NetworkctlTests)
> 23:06:55 ----------------------------------------------------------------------
> 23:06:55 Traceback (most recent call last):
> 23:06:55   File "./test/test-network/systemd-networkd-tests.py", line 665, in test_altname
> 23:06:55     self.wait_online(['dummy98:degraded'])
> 23:06:55   File "./test/test-network/systemd-networkd-tests.py", line 602, in wait_online
> 23:06:55     check_output(*args, env=env)
> 23:06:55   File "./test/test-network/systemd-networkd-tests.py", line 50, in check_output
> 23:06:55     return subprocess.check_output(command, universal_newlines=True, **kwargs).rstrip()
> 23:06:55   File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
> 23:06:55     **kwargs).stdout
> 23:06:55   File "/usr/lib64/python3.6/subprocess.py", line 438, in run
> 23:06:55     output=stdout, stderr=stderr)
> 23:06:55 subprocess.CalledProcessError: Command '['/usr/lib/systemd/systemd-networkd-wait-online', '--timeout=20s', '--interface=dummy98:degraded']' returned non-zero exit status 1.
> ```
> 
> Any idea about this one?

Hopefully addressed by the last cherry-picked commit.

**Comment by bluca** [comment]
Thank you, missed that

**Comment by yuwata** [comment]
Oh, thank you. I completely forgot what I did. Hehe...

**Pull request merged**
