### PR TITLE
V255 stable batch

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by keszybz** [comment]
mkosi/ci (centos 9) failed when downloading repos.

**Comment by mrc0mmand** [comment]
Btw, for https://github.com/systemd/systemd-stable/pull/385#issuecomment-2074179416 and https://github.com/systemd/systemd-stable/pull/383#issuecomment-2057814286 you could backport just the test skip commit - 8ed7800d7b0674c278513968e1bea1ebd4320c4f - to reduce the noise in CI.

**Comment by bluca** [comment]
I'll do another PR after this, with that and https://github.com/systemd/systemd/pull/31311

**Comment by keszybz** [comment]
Merged. We don't want to wait for ubuntuautopkgtests, and the rest passed.

**Pull request merged**
