### PR TITLE
[v250] Latest round of fixes till 2022/03/04

### PR DESCRIPTION
**Pull request by bluca**

### CODE REVIEW

**Review by yuwata — APPROVED** [review]

**Comment by mrc0mmand** [comment]
Looking at the CentOS CI results, I guess d10d562bd4b9f93130fb2b23f2b0d0d4126ea7d4 should be backported as well.

**Comment by bluca** [comment]
thanks, added

**Comment by mrc0mmand** [comment]
I am afraid we need d490188b8f6da658d8086dd53b7db95735e5cca1 as well <sup>sorry<sup>this is definitely the last one</sup></sup>

**Comment by bluca** [comment]
That's already included - there was a conflict, did I resolve it wrong?

**Comment by mrc0mmand** [comment]
Ugh, nevermind, I accidentally opened log from my test PR (#173) which doesn't have that commit, sorry :facepalm:

**Comment by bluca** [comment]
No worries! I imagine this is the usual known issue?

```
16:25:01 FAILED TASKS:
16:25:01 -------------
16:25:01 TEST-64-UDEV-STORAGE
```

**Comment by mrc0mmand** [comment]
*Oh no*, I suspect that should be fixed by b034f02c628057c30a2136289a1b388a6fb9a737.

**Comment by bluca** [comment]
thanks, added

**Review by mrc0mmand — APPROVED** [review]
Looking at the intermediate CI results it looks like even CentOS CI is content (for now), so I'll add my *seal of approval* as well. Thanks<sup>for the patience</sup>!

**Comment by bluca** [comment]
Nice, thanks for enabling it for this repo!

**Comment by mrc0mmand** [comment]
> Nice, thanks for enabling it for this repo!

No problem! The sanitizer job will be kind of slow on the stable repo, since it runs both parts (clang and gcc) in once job, contrary to the systemd repo, where only the clang part is run for PRs and the gcc one runs in the daily cron job. But given this repo is pretty low-traffic, it shouldn't be an issue.

**Pull request merged**
