### PR TITLE
V243 stable fixes

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

**Comment by yuwata** [comment]
@evverx Semaphore CI seems to be broken...

**Comment by evverx** [comment]
@yuwata to make it work the scripts from the systemd repository on Semaphore side should be moved to systemd-stable there and `semaphore-runner.sh` should be backported to every stable branch. We kind of started to discuss how to do that properly in https://github.com/systemd/systemd-stable/issues/24#issuecomment-527900346 but haven't figured it out yet as far as I know.

**Comment by keszybz** [comment]
I pushed a rebased version with some more patches.

**Comment by yuwata** [comment]
OK. Thanks.

**Pull request closed without merging**
